In [20]:
"Consider the below code to answer further questions:"
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [ ]:
"""Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables."""

In [21]:
print(list_)

['1', '2', '3', '4', '5']


In [34]:
print(type(list_))

<class 'list'>


In [ ]:
# list_ is of list data type

In [16]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [18]:
print(array_list.dtype)

<U1


In [ ]:
# data type of array_list is U1 i.e. uint8 i.e. it is 8-bit unsigned integer

In [33]:
"""Q2. Write a code to print the data type of each and every element of both the variables list_ and
array_list."""
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [35]:
for i in array_list:
    print(i.dtype)

<U1
<U1
<U1
<U1
<U1


In [42]:
"""
Q3. Considering the following changes in the variable, array_list:"""

array_list = np.array(object = list_, dtype = int)

"""Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
"""

# data type of list_ variable will remain same but data type of array_list will change to int
print("Type of array_list variable:")
for i in array_list:
    print(type(i))
    
print("\nType of list_ variables:")
for i in list_:
    print(type(i))

Type of array_list variable:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>

Type of list_ variables:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [43]:
"Consider the below code to answer further questions:"
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [47]:
"""
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size
"""
print("Shape of num_array is:", num_array.shape)
print("Size of num_array is:", num_array.size)

Shape of num_array is: (2, 3)
Size of num_array is: 6


In [54]:
"""
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]
"""
data = np.zeros((3,3))
size = np.size
print(np.matrix(data))
print("Size of array is:",data.size)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Size of array is: 9
